/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package home;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

/**
 *
 * @author Dell
 */
public class Home extends HttpServlet {

    protected void service(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        response.setHeader("cache-control", "no-cache, no-store, must-revalidate");
        HttpSession session = request.getSession();
        if (session.getAttribute("user_type") != null) {
            if (session.getAttribute("user_type").toString().equalsIgnoreCase("admin")) {
                response.sendRedirect("Admin");
            } else if (session.getAttribute("user_type").toString().equalsIgnoreCase("doctor")) {
                response.sendRedirect("DoctorDashboard");
            } else if (session.getAttribute("user_type").toString().equalsIgnoreCase("patient")) {
                response.sendRedirect("Dashboard");
            }
        }
        PrintWriter out = response.getWriter();
        try {
            out.println("<!DOCTYPE html>"
                    + "<html lang=\"en\">"
                    + "<head>"
                    + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">"
                    + "<meta name=\"description\" content=\"\">"
                    + "<meta name=\"author\" content=\"\">"
                    + "<title>Hospital Management System</title>"
                    + "<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">"
                    + "<link href=\"https://fonts.googleapis.com/css?family=Lato:400,100,100italic,300,300italic,400italic,700,700italic,900,900italic\" rel=\"stylesheet\" type=\"text/css\">"
                    + "<link href=\"https://fonts.googleapis.com/css?family=Roboto:400,100,300,100italic,300italic,400italic,500,500italic,700,700italic,900,900italic\" rel=\"stylesheet\" type=\"text/css\">"
                    + "<link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">"
                    + "<link href=\"js/plugins/camera/css/camera.css\" rel=\"stylesheet\">"
                    + "<link href=\"js/plugins/magnific-popup/magnific-popup.css\" rel=\"stylesheet\">"
                    + "<link href=\"js/plugins/range-slider/css/bootstrap-slider.min.css\" rel=\"stylesheet\">"
                    + "<link href=\"css/style.css\" rel=\"stylesheet\">"
                    + "<link href=\"css/responsive.css\" rel=\"stylesheet\">"
                    + "</head>"
                    + "<body>"
                    + "<header class=\"main-header\">"
                    + "<div class=\"container px-md-0\">"
                    + "<div class=\"top-bar d-none d-md-block\">"
                    + "<div class=\"row\">"
                    + "<div class=\"col-md-6 col-sm-12\">"
                    + "<span>Opening Hours:</span>  Mon To Fri - 9:00 - 20:00, Sat &amp; Sun - 10:00 - 15:00"
                    + "</div>"
                    + "<div class=\"col-md-6 col-sm-12\">"
                    + "<ul class=\"list-unstyled list-inline\">"
                    + "<li class=\"list-inline-item\"><a href=\"mailto:care@yourhosptialsname.com\">"
                    + "<i class=\"fa fa-envelope-o\"></i>"
                    + "care@yourhosptialsname.com"
                    + "</a></li>"
                    + "<li class=\"list-inline-item\"><i class=\"fa fa-phone\"></i> Call Us: 9998887771</li>"
                    + "</ul>"
                    + "</div>"
                    + "</div>"
                    + "</div>"
                    + "<nav id=\"nav\" class=\"navbar navbar-expand-lg\" role=\"navigation\">"
                    + "<div class=\"container px-md-0\">"
                    + "<a href=\"Home\" class=\"navbar-brand\">"
                    + "<i class=\"fa fa-heartbeat\"></i>"
                    + "HMS"
                    + "</a>"
                    + "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#mainNav\" aria-controls=\"mainNav\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">"
                    + "<span class=\"navbar-toggler-icon fa fa-bars\"></span>"
                    + "</button>"
                    + "<div id=\"mainNav\" class=\"navbar-collapse collapse\">"
                    + "<ul class=\"nav navbar-nav ml-auto\">"
                    + "<li class=\"nav-item active\">"
                    + "<a href=\"Home\" class=\"nav-link\">Home</a>"
                    + "</li>"
                    + "<li class=\"nav-item\">"
                    + "<a href=\"about\" class=\"nav-link\">"
                    + "About"
                    + "</a>"
                    + "</li>"
                    + "<li class=\"nav-item\">"
                    + "<a href=\"feedback\" class=\"nav-link\">"
                    + "Feedback"
                    + "</a>"
                    + "</li>"
                    + "<li class=\"nav-item\">"
                    + "<a href=\"Login\" class=\"nav-link\">"
                    + "Login"
                    + "</a>"
                    + "</li>"
                    + "<li class=\"nav-item\">"
                    + "<a href=\"Register\" class=\"nav-link\">"
                    + "Register"
                    + "</a>"
                    + "</li>"
                    + "</ul>"
                    + "</div>"
                    + "</div>"
                    + "</nav>"
                    + "</div>"
                    + "</header>"
                    + "<section class=\"main-slider clearfix\">"
                    + "<div id=\"camera_wrap_1\" class=\"camera_wrap camera_white_skin\">"
                    + "<div data-src=\"images/slider/slider-img1.jpg\">"
                    + "<div class=\"camera_caption fadeFromLeft d-none d-md-block\">"
                    + "<h2>One Stop Solution</h2>"
                    + "<h2>For All <span>Medical Needs</span></h2>"
                    + "<p>The Online Doctor Appointment System is Online Web Based Appointment System by which patient and doctor can interact with each other without any problem."
                    + "</p>"
                    + "<a href=\"#services-sec\" class=\"btn btn-1\">View Services</a>"
                    + "</div>"
                    + "</div>"
                    + "<div data-src=\"images/slider/slider-img2.jpg\">					"
                    + "<div class=\"camera_caption fadeFromLeft d-none d-md-block\">"
                    + "<h2>One Stop Solution</h2>"
                    + "<h2>For All <span>Medical Needs</span></h2>"
                    + "<p>The Online Doctor Appointment System is Online Web Based Appointment System by which patient and doctor can interact with each other without any problem."
                    + "</p>"
                    + "<a href=\"#services-sec\" class=\"btn btn-1\">View Services</a>"
                    + "</div>"
                    + "</div>"
                    + "<div data-src=\"images/slider/slider-img3.jpg\">"
                    + "<div class=\"camera_caption fadeFromLeft d-none d-md-block\">"
                    + "<h2>One Stop Solution</h2>"
                    + "<h2>For All <span>Medical Needs</span></h2>"
                    + "<p>The Online Doctor Appointment System is Online Web Based Appointment System by which patient and doctor can interact with each other without any problem."
                    + "</p>"
                    + "<a href=#services-sec\" class=\"btn btn-1\">View Services</a>"
                    + "</div>"
                    + "</div>"
                    + "</div>"
                    + "</section>"
                    + "<div class=\"container px-md-0 main-container\">"
                    + "<div class=\"notification-boxes row\">"
                    + "<div class=\"col-lg-3 col-md-6 col-sm-12\">"
                    + "<div class=\"box\">"
                    + "<i class=\"fa fa-user-md\"></i>"
                    + "<h4>Qualified Doctors</h4>"
                    + "<p>"
                    + "All the doctors are having more than 10 years of experince in their fields."
                    + "</p>"
                    + "<a href=\"#\" class=\"btn btn-transparent\">Read More</a>"
                    + "</div>"
                    + "</div>"
                    + "<div class=\"col-lg-3 col-md-6 col-sm-12\">"
                    + "<div class=\"box\">"
                    + "<i class=\"fa fa-stethoscope\"></i>"
                    + "<h4>Regular Checkup</h4>"
                    + "<p>"
                    + "We have facilitiy of regular checkup for our patients free of cost."
                    + "</p>"
                    + "<a href=\"#\" class=\"btn btn-transparent\">Read More</a>"
                    + "</div>"
                    + "</div>"
                    + "<div class=\"col-lg-3 col-md-6 col-sm-12\">"
                    + "<div class=\"box\">"
                    + "<i class=\"fa fa-flask\"></i>"
                    + "<h4>Lab Test</h4>"
                    + "<p>"
                    + "We provide all type of lab test such as blood test, Echocardiography etc."
                    + "</p>"
                    + "<a href=\"#\" class=\"btn btn-transparent\">Read More</a>"
                    + "</div>"
                    + "</div>"
                    + "<div class=\"col-lg-3 col-md-6 col-sm-12\">"
                    + "<div class=\"box\">"
                    + "<i class=\"fa fa-comments-o\"></i>"
                    + "<h4>Clinic News</h4>"
                    + "<p>"
                    + "We are up online now. Just register then login to take our service from home."
                    + "</p>"
                    + "<a href=\"#\" class=\"btn btn-transparent\">Read More</a>"
                    + "</div>"
                    + "</div>"
                    + "</div>"
                    + "<section class=\"welcome-area\">"
                    + "<div class=\"row\">"
                    + "<div class=\"col-md-6 col-sm-12\">"
                    + "<h2 class=\"main-heading1 lite\">We Offer Fast &amp; Reliable</h2>"
                    + "<h2 class=\"main-heading2\">Medical &amp; Healthcare Needs</h2>"
                    + "<p>The Online Doctor Appointment System is Online Web Based Appointment System by which patient and doctor can servicing their client .:"
                    + "This system is to make patient easier to get service of doctor. "
                    + "This system has feature to allow client for taken appointment of doctor from their place.  "
                    + "This system offers an effective solution where user can view various booking slot available and select the preferred date and time.  "
                    + "This system helps to reduce the waiting time of the patient. "
                    + "This system is very user friendly. "
                    + "</p>"
                    + "</div>"
                    + "<div class=\"col-md-6 col-sm-12\">"
                    + "<img src=\"images/image1.jpg\" alt=\"image\" class=\"img-fluid img-style1\">"
                    + "</div>"
                    + "</div>"
                    + "</section>"
                    + "</div>"
                    + "<div class=\"container px-md-0 main-container\" id=\"services-sec\">"
                    + "<section class=\"medical-services\">"
                    + "<h2 class=\"main-heading1 lite\">Our Best</h2>"
                    + "<h2 class=\"main-heading2\">Medical Services</h2>"
                    + "<ul class=\"list-unstyled row text-center\">"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/band-aid.png\" alt=\"Band Aid\">"
                    + "</div>"
                    + "<h5>First Aid</h5>"
                    + "</li>"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/tooth.png\" alt=\"Dental Care\">"
                    + "</div>"
                    + "<h5>Dental Care</h5>"
                    + "</li>"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/ambulance.png\" alt=\"24x7 Ambulance\">"
                    + "</div>"
                    + "<h5>24x7 Ambulance</h5>"
                    + "</li>"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/nurse.png\" alt=\"Qualified Doctors\">"
                    + "</div>"
                    + "<h5>Qualified Doctors</h5>"
                    + "</li>"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/saline-bottle.png\" alt=\"Medical Pharmacy\">"
                    + "</div>"
                    + "<h5>Medical Pharmacy</h5>"
                    + "</li>"
                    + "<li class=\"col-lg-2 col-md-4 col-sm-12\">"
                    + "<div class=\"icon\">"
                    + "<img src=\"images/icons/stethoscope.png\" alt=\"Pulmonary\">"
                    + "</div>"
                    + "<h5>Pulmonary</h5>"
                    + "</li>"
                    + "</ul>"
                    + "</section>"
                    + "</div>"
                    + "<footer class=\"main-footer\">"
                    + "<div class=\"copyright\">"
                    + "<div class=\"container px-md-0 clearfix text-center \">"
                    + "<p class=\"float-md-left mb-2 mb-md-0 text-center\">"
                    + "&copy; Copyright 2019. AlL Rights Reserved By <span>HMS</span>"
                    + "</p>"
                    + "</div>"
                    + "</div>"
                    + "</footer>"
                    + "<script src=\"js/jquery-3.3.1.min.js\"></script>"
                    + "<script src=\"js/popper.min.js\"></script>"
                    + "<script src=\"js/bootstrap.min.js\"></script>"
                    + "<script src=\"js/plugins/camera/js/jquery.mobile.customized.min.js\"></script>"
                    + "<script src=\"js/plugins/camera/js/jquery.easing.1.3.js\"></script>"
                    + "<script src=\"js/plugins/camera/js/camera.min.js\"></script>	"
                    + "<script src=\"js/plugins/shuffle/jquery.shuffle.modernizr.min.js\"></script>"
                    + "<script src=\"js/plugins/magnific-popup/jquery.magnific-popup.min.js\"></script>"
                    + "<script src=\"js/plugins/range-slider/js/bootstrap-slider.min.js\"></script>"
                    + "<script src=\"https://maps.googleapis.com/maps/api/js\"></script>	"
                    + "<script src=\"js/custom.js\"></script>"
                    + "</body>"
                    + "</html>");
        } finally {
            out.close();
        }
    }
}
