/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;

/**
 *
 * @author Vineet Tiwari
 */
public class Admin extends HttpServlet {

    protected void service(HttpServletRequest request, HttpServletResponse response) {
        try {
            PrintWriter out = response.getWriter();
            response.setHeader("cache-control", "no-cache, no-store, must-revalidate");
            HttpSession session = request.getSession();
            if (session.getAttribute("user_type") != null) {
                if (session.getAttribute("user_type").toString().equalsIgnoreCase("admin")) {

                    response.setContentType("text/html");
                    out.println("<!DOCTYPE html>"
                            + "<html lang=\"en\">"
                            + "<head>"
                            + "<meta charset=\"utf-8\">"
                            + "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
                            + "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">"
                            + "<meta name=\"description\" content=\"\">"
                            + "<meta name=\"author\" content=\"\">"
                            + "<title>Dashboard | Admin | Hosptital Management System</title>"
                            + "<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.2/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">"
                            + "<link href=\"https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i\" rel=\"stylesheet\">"
                            + "<link href=\"css/sb-admin-2.min.css\" rel=\"stylesheet\">"
                            + "</head>"
                            + "<body id=\"page-top\">"
                            + "<div id=\"wrapper\">"
                            + "<ul class=\"navbar-nav bg-gradient-primary sidebar sidebar-dark accordion\" id=\"accordionSidebar\">"
                            + "<a class=\"sidebar-brand d-flex align-items-center justify-content-center\" href=\"Admin\">"
                            + "<div class=\"sidebar-brand-icon rotate-n-15\">"
                            + "<i class=\"fas fa-laugh-wink\"></i>"
                            + "</div>"
                            + "<div class=\"sidebar-brand-text mx-3\">HMS</div>"
                            + "</a>"
                            + "<hr class=\"sidebar-divider my-0\">"
                            + "<li class=\"nav-item active\">"
                            + "<a class=\"nav-link\" href=\"Admin\">"
                            + "<i class=\"fas fa-fw fa-tachometer-alt\"></i>"
                            + "<span>Dashboard</span></a>"
                            + "</li>"
                            + "<hr class=\"sidebar-divider\">"
                            + "<li class=\"nav-item\">"
                            + "<a class=\"nav-link\" href=\"RegisterDoctor\">"
                            + "<i class=\"fas fa-user-md\"></i>"
                            + "<span>Add Doctor</span></a>"
                            + "</li>"
                            + "<li class=\"nav-item\">"
                            + "<a class=\"nav-link\" href=\"DoctorsList\">"
                            + "<i class=\"fas fa-users\"></i>"
                            + "<span>Doctors List</span></a>"
                            + "</li>"
                            + "<li class=\"nav-item\">"
                            + "<a class=\"nav-link\" href=\"PatientsList\">"
                            + "<i class=\"fas fa-wheelchair\"></i>"
                            + "<span>Patient List</span></a>"
                            + "</li>"
                            + "<li class=\"nav-item\">"
                            + "<a class=\"nav-link\" href=\"ChangePassword\">"
                            + "<i class=\"fas fa-wrench\"></i>"
                            + "<span>Change Password</span></a>"
                            + "</li>"
                            + "</ul>"
                            + "<div id=\"content-wrapper\" class=\"d-flex flex-column\">"
                            + "<div id=\"content\">"
                            + "<nav class=\"navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow\">"
                            + "<ul class=\"navbar-nav ml-auto\">"
                            + "<li class=\"nav-item dropdown no-arrow\">"
                            + "<a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"userDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">"
                            + "<span class=\"mr-2 d-lg-inline text-gray-600 small\">Admin <i class=\"fas fa-user\"></i></span>"
                            + "</a>"
                            + "<div class=\"dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"userDropdown\">"
                            + "<a class=\"dropdown-item\" href=\"#\" data-toggle=\"modal\" data-target=\"#logoutModal\">"
                            + "<i class=\"fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400\"></i>"
                            + "Logout"
                            + "</a>"
                            + "</div>"
                            + "</li>"
                            + "</ul>"
                            + "</nav>"
                            + "<div class=\"container-fluid\">"
                            + "<div class=\"d-sm-flex align-items-center justify-content-between mb-4\">"
                            + "<h1 class=\"h3 mb-0 text-gray-800\">Dashboard</h1>"
                            + "</div>"
                            + "<div class=\"row\">"
                            + "<div class=\"col-xl-3 col-md-6 mb-4\">"
                            + "<div class=\"card border-left-primary shadow h-100 py-2\">"
                            + "<div class=\"card-body\">"
                            + "<div class=\"row no-gutters align-items-center\">"
                            + "<div class=\"col mr-2\">"
                            + "<div class=\"text-xs font-weight-bold text-primary text-uppercase mb-1\">Total Doctors</div>"
                            + "<div class=\"h5 mb-0 font-weight-bold text-gray-800\">40,000</div>"
                            + "</div>"
                            + "<div class=\"col-auto\">"
                            + "<i class=\"fas fa-user-md fa-2x text-gray-300\"></i>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<div class=\"col-xl-3 col-md-6 mb-4\">"
                            + "<div class=\"card border-left-success shadow h-100 py-2\">"
                            + "<div class=\"card-body\">"
                            + "<div class=\"row no-gutters align-items-center\">"
                            + "<div class=\"col mr-2\">"
                            + "<div class=\"text-xs font-weight-bold text-success text-uppercase mb-1\">Total Patient</div>"
                            + "<div class=\"h5 mb-0 font-weight-bold text-gray-800\">215,000</div>"
                            + "</div>"
                            + "<div class=\"col-auto\">"
                            + "<i class=\"fas fa-wheelchair fa-2x text-gray-300\"></i>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + ""
                            + "<div class=\"col-xl-3 col-md-6 mb-4\">"
                            + "<div class=\"card border-left-info shadow h-100 py-2\">"
                            + "<div class=\"card-body\">"
                            + "<div class=\"row no-gutters align-items-center\">"
                            + "<div class=\"col mr-2\">"
                            + "<div class=\"text-xs font-weight-bold text-info text-uppercase mb-1\">Appointments</div>"
                            + "<div class=\"row no-gutters align-items-center\">"
                            + "<div class=\"col-auto\">"
                            + "<div class=\"h5 mb-0 mr-3 font-weight-bold text-gray-800\">50</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<div class=\"col-auto\">"
                            + "<i class=\"fas fa-clipboard-list fa-2x text-gray-300\"></i>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<div class=\"col-xl-3 col-md-6 mb-4\">"
                            + "<div class=\"card border-left-warning shadow h-100 py-2\">"
                            + "<div class=\"card-body\">"
                            + "<div class=\"row no-gutters align-items-center\">"
                            + "<div class=\"col mr-2\">"
                            + "<div class=\"text-xs font-weight-bold text-warning text-uppercase mb-1\">Pending Appoitment</div>"
                            + "<div class=\"h5 mb-0 font-weight-bold text-gray-800\">18</div>"
                            + "</div>"
                            + "<div class=\"col-auto\">"
                            + "<i class=\"fas fa-exclamation fa-2x text-gray-300\"></i>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<div class=\"row\">"
                            + "<div class=\"col-xl-12 col-lg-12\">"
                            + "<div class=\"card shadow mb-4\">"
                            + "<div class=\"card-header py-3 d-flex flex-row align-items-center justify-content-between\">"
                            + "<h6 class=\"m-0 font-weight-bold text-primary\">Welcome</h6>"
                            + "</div>"
                            + "<div class=\"card-body\">"
                            + "<p class=\"text-center\" style=\"font-size: 24px; font-weight: bold; margin-top: 80px;\">Welcome to your dashboard.</p>"
                            + "<p class=\"text-center\" style=\"font-size: 18px; margin-bottom: 80px;\">You can manage all the doctors as well as patients to !</p>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<footer class=\"sticky-footer bg-white\">"
                            + "<div class=\"container my-auto\">"
                            + "<div class=\"copyright text-center my-auto\">"
                            + "<span>Copyright &copy; Hospital Management System 2019</span>"
                            + "</div>"
                            + "</div>"
                            + "</footer>"
                            + "</div>"
                            + "<a class=\"scroll-to-top rounded\" href=\"#page-top\">"
                            + "<i class=\"fas fa-angle-up\"></i>"
                            + "</a>"
                            + "<div class=\"modal fade\" id=\"logoutModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">"
                            + "<div class=\"modal-dialog\" role=\"document\">"
                            + "<div class=\"modal-content\">"
                            + "<div class=\"modal-header\">"
                            + "<h5 class=\"modal-title\" id=\"exampleModalLabel\">Ready to Leave?</h5>"
                            + "<button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">"
                            + "<span aria-hidden=\"true\">×</span>"
                            + "</button>"
                            + "</div>"
                            + "<div class=\"modal-body\">Select \"Logout\" below if you are ready to end your current session.</div>"
                            + "<div class=\"modal-footer\">"
                            + "<button class=\"btn btn-secondary\" type=\"button\" data-dismiss=\"modal\">Cancel</button>"
                            + "<a class=\"btn btn-primary\" href=\"Logout\">Logout</a>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "</div>"
                            + "<script src=\"js/jquery-3.3.1.min.js\"></script>"
                            + "<script src=\"js/bootstrap.bundle.min.js\"></script>"
                            + "<script src=\"js/jquery.easing.min.js\"></script>"
                            + "<script src=\"js/sb-admin-2.min.js\"></script>"
                            + "</body>"
                            + "</html>");
                } else {
                    response.sendRedirect("Home");
                }
            } else {
                response.sendRedirect("Home");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
